### ISSUE TITLE
Not implemented strategy

### ISSUE THREAD

**Issue by mantasavas** [mantasavas/trading-strategy-automation#1]
Forgot to implent double bollinger band strategy!

**Comment by mantasavas** [comment]
Implemented

**Comment by redallica** [comment]
Hey @mantasavas 

Thanks for putting this repository with BB and ADX indicators.
Is there a way to make the time period for ADX not hard coded at 14, but make it a variable so we can test it with different values ? That would make it even better.

**Comment by mantasavas** [comment]
Hey @redallica,

I really appreciate that you took a look at my work and found a great insight on how it can be improved. Yes, it should be easily changed to any interval you wish for, not only 14. But as far as I can see (and remember), I would need to change a few places in the code and as it was for my deadline in University, I rushed a bit with ADX implementation (so don't take it too seriously even though it works correctly). After 8 months I barely can recall mechanics behind ADX algorithm and a bit afraid to mislead you or make mistake in code, need to refresh my knowledge again, before changing the code :)
